OBJS = src\\JackAnalyzer.c src\\JackTokenizer.c src\\CompilationEngine.c src\\SymbolTable.c src\\VMWriter.c
OBJ_NAME = MyJackCompiler
flag = -static
all: $(OBJS)
		gcc $(flag) $(OBJS) -o $(OBJ_NAME) 
